urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from mysite.views import hello, current_datetime, hours_ahead, display_meta
from mysite.books import views
from mysite.contacts import views as contact_views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^hello/$', hello),
    (r'^time/$', current_datetime),
    (r'^time/plus/(\d{1,2})/$', hours_ahead),
    (r'^displaymeta/$', display_meta),
    (r'^search/$', views.search),
    (r'^contact/$', contact_views.contact),
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

books/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-mail')

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.title

contacts/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your email address')
    message = forms.CharField(widget=form.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough word!")
        return message

books/views.py
from django.shortcuts import render_to_response
from django.http import Http404, HttpResponse
from mysite.books.models import Book

def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter a most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('search_results.html', {'books': books, 'query': q})
    return render_to_response('search_form.html', {'errors': errors})

contacts/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from mysite.contacts.forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
                initial={'subject': 'I love your site!'}
            )
    return render_to_response('contact_form.html', {'form': form})

views.py
from django.shortcuts import render_to_response
from django.http import Http404, HttpResponse
import datetime

def hello(request):
    return HttpResponse("Hello World")

def current_datetime(request):
    current_date = datetime.datetime.now()
    return render_to_response('dateapp/current_datetime.html', locals())

def hours_ahead(request, hour_offset):
    try:
        hour_offset = int(hour_offset)
    except ValueError:
        raise Http404()
    next_time = datetime.datetime.now() + datetime.timedelta(hours=hour_offset)
    return render_to_response('dateapp/hours_ahead.html', locals())

def display_meta(request):
    meta_values = request.META.items()
    meta_values.sort()
    return render_to_response('chap7app/diaplaymeta.html', locals())

templates/chap7app/diaplaymeta.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang-"en">
    <head>
        <title>Display META</title>
    </head>
    <body>
        <h1>Display META</h1>
        <h2>request.path = {{ request.path }}</h2>
        <h2>request.get_host = {{ request.get_host }}</h2>
        <h2>request.get_full_path = {{ request.get_full_path }}</h2>
        <h2>request.is_secure = {{ request.is_secure }}</h2>
        <table>
            {% for k, v in meta_values %}
                <tr><td>{{ k }}</td><td>{{ v }}</td></tr>
            {% endfor %}
        </table>
    </body>
</html>

templates/contact_form.html
<html>
    <head>
        <title>Contact Us</title>
    </head>
    <body>
        <h1>Contact Us</h1>

        {% if errors %}
            <p style="color: red;">
                Please correct the error{{ form.errors|pluralize }} below.
            </p>
        {% endif %}

        <form action="" method="post">
            <div class="field">
                {{ form.subject.errors }}
                <label for="id_subject">Subject:</label>
                {{  form.subject }}
            </div>
            <div class="field">
                {{ form.email.errors }}
                <label for="id_mail">Your e-mail address:</label>
                {{ form.email }}
            </div>
            <div class="field{% if form.message.errors %} errors{% endif %}">
                {% if form.message.errors %}
                    <ul>
                        {% for error in form.message.errors %}
                            <li><strong>{{ error }} </strong></li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <label for="id_message">Massage:</label>
                {{ form.message }}
            </div>
            <input type="submit" value="Submit" >
        </form>

    </body>
</html>

templates/dateapp/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang-"en">
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <h1>My helpful timestamp site.</h1>
        {% block content %}{% endblock %}
        {% block footer %}
        <hr>
        <p>Thanks for visting my site.</p>
        {% endblock %}
    </body>
</html>

templates/dateapp/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time.{% endblock %}

{% block content%}
<p>It is now {{ current_date }}.</p>
{% endblock %}

templates/dateapp/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}

templates/search_form.html
<html>
    <head>
        <title>Search</title>
    </head>
    <body>
        {% if errors %}
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="" method="get">
            <input type="text" name="q">
            <input type="submit" value="Search">
        </form>
    </body>
</html>

templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong><p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}